config/routes.rb
Rails.application.routes.draw do
  resources :publications
  resources :postulations, only: [:create]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :publication
  belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum :role, [:normal_user, :author, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, 
    :position, :note, :photo])
    end

    def authorize_request(kind = nil)
        unless kind.include?(current_user.role)
        redirect_to root_path, notice: "You are not authorized to perform this action"
        end
    end


end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController
    def create
        @publication = Publication.find(params[:postulation][:publication_id])
        @postulation = Postulation.new(postulation_params)
        @postulation.user = current_user
        respond_to do |format|
            if @postulation.save
            format.html { redirect_to publication_path(@publication.id), notice:
            'Postulation was successfully created.' }
            else
            format.html { redirect_to publication_path(@publication.id), notice:
            'Postulation was not created.' }
            end
        end
    end

    private
    def postulation_params
        params.require(:postulation).permit(:content, :publication_id)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action only: [:new, :create, :edit, :update, :destroy] do
    authorize_request(["author", "admin"])
    end

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @postulation = Postulation.new
    #@postulations = @publication.postulations
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postulations_helper.rb
module PostulationsHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfertasLaborales</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# -- bootsratp -- %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%# -- js bootstrap --  %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <p class="notice", style="color: green"><%= notice %></p>
    <p class="alert", style="color: red"><%= alert %></p>

    
    <div class="container">
    <%= yield %>
    </div>
    
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/postulations/_form.html.erb
<%= form_with(model: @postulation, local: true) do |f| %>
    <% if @postulation.errors.any? %>
        <div id = 'error_explanation'>
        <h2>Este comentario no se pudo crear por las siguientes
        razones</h2>
            <ul>
            <% @postulation.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.hidden_field :publication_id, value: @publication.id %>
    <div class = 'field'>
        <%= f.label :content, as: "Contenido" %>
        <%= f.text_field :content %>
    </div>
    <div class = 'actions'>
        <%= f.submit %>
    </div>
<% end %>

app/views/postulations/_publication_postulations.html.erb
<div>
<% @postulations.each do |postulation| %>
    <p>
    <%= image_tag(postulation.user.photo) %>
    <%= postulation.content %>
    </p>
<% end %>
</div>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <strong>Title:</strong>
    <%= publication.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= publication.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= publication.user_id %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<h1>Publications</h1>

<div id="publications">
  <% @publications.each do |publication| %>
    <%= render publication %>
    <p>
      <%= link_to "Show this publication", publication %>
    </p>
  <% end %>
</div>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<%= render @publication %>
<%= render 'postulations/form' %>

<%#= render 'postulations/publication_postulations' %>
<div>
  <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
  <%= link_to "Back to publications", publications_path %>

  <%= button_to "Destroy this publication", @publication, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<%# pie de pagina %>
<%#  <footer class="my-5 py-5 px-5 bg-black">  %>
  
  <footer class="bg-light">
    <h4 class="text-center text-secondary">Sergio Dominguez 2023. Todos los derechos reservados.</h4>
  </footer>

app/views/shared/_navbar.html.erb
<!-- barra navegacion -->
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to 'Ofertas Laborales', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to "New publication", new_publication_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                <%= link_to 'Actualizar usuario', edit_user_registration_path, class: 'nav-link'%>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                    <% if user_signed_in? %>
                        Hola <%= current_user.email %>
                    <% else %>
                        Dale registrate o conectate
                    <% end %>
                </a>
                        <ul class="dropdown-menu">
                            <% if user_signed_in? %>
                                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item',
                            method: :delete %></li>
                            <% else %>
                                <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
                            <% end %>
                        </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>